In [1]:
import numpy as np


In [6]:
my_list1 = [1,2,3,4]

In [7]:
my_array1 = np.array(my_list1)

In [8]:
my_array1

array([1, 2, 3, 4])

In [9]:
my_list2 = [2,4,6,7]

In [11]:
final_list = [my_list1,my_list2]

In [12]:
final_list

[[1, 2, 3, 4], [2, 4, 6, 7]]

In [13]:
my_array2 = np.array(final_list)

In [14]:
my_array2

array([[1, 2, 3, 4],
       [2, 4, 6, 7]])

In [17]:
my_array2.shape

(2, 4)

In [18]:
my_array2.dtype

dtype('int32')

In [24]:
my_zeros = np.zeros(5)
my_zeros

array([0., 0., 0., 0., 0.])

In [25]:
my_zeros.dtype

dtype('float64')

In [27]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [34]:
np.arange(2,80,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78])