# Numpy

In [60]:
import numpy as np


In [61]:
a = np.array([2,3,4,6,2])
a

array([2, 3, 4, 6, 2])

In [62]:
b = np.array([[2,3,4,6,2],[4,5,6,9,4],[22,33,44,55,99]])
b.shape
print(b)
b.shape

[[ 2  3  4  6  2]
 [ 4  5  6  9  4]
 [22 33 44 55 99]]


(3, 5)

In [63]:
a.shape

(5,)

In [64]:
b.ndim


2

In [95]:
c = np.array([2,3,4.2,6,2])
c

array([2. , 3. , 4.2, 6. , 2. ])

In [101]:
type(c)
c.dtype


dtype('float64')

In [67]:
a.size


5

In [68]:
type(a)


numpy.ndarray

In [69]:
b = np.array([6, 7, 8.0,'a'])
b

array(['6', '7', '8.0', 'a'], dtype='<U32')

In [70]:
a = np.array([1,2,3,4])  # RIGHT
a

array([1, 2, 3, 4])

In [71]:
# array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [72]:
#The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2.2], [3,4] ], dtype=int )
c

array([[1, 2],
       [3, 4]])

In [73]:
data=np.arange(10,100,5)
data

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [74]:
#The function zeros creates an array full of zeros
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
#universal functions such as sqrt, sin, cos etc.,
d = np.arange(30).reshape(5,6)
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [76]:
#Indexing Arrays
a = np.arange(90000).reshape(900,100)**40
a


array([[          0,           1,           0, ...,  1599192833,
                  0,   -26821343],
       [          0, -1283372959,           0, ..., -1662583967,
                  0,  2116887489],
       [          0,   907199041,           0, ...,   379799873,
                  0, -1652840479],
       ...,
       [          0, -1962657695,           0, ...,   166194017,
                  0, -1133710399],
       [          0,  -554175935,           0, ...,  1295415617,
                  0, -1231702047],
       [          0,   720165281,           0, ...,   940610721,
                  0,  -486089343]], dtype=int32)

In [77]:
#Shape Manipulation

a = np.arange(12)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
a = np.arange(4).reshape(2,2)
b = np.arange(11,15).reshape(2,2)
print(a)
print(b)


[[0 1]
 [2 3]]
[[11 12]
 [13 14]]


In [80]:
c=np.vstack((a,b))
print(c)
c.shape

[[ 0  1]
 [ 2  3]
 [11 12]
 [13 14]]


(4, 2)

In [81]:
np.hstack((a,b))


array([[ 0,  1, 11, 12],
       [ 2,  3, 13, 14]])

In [82]:
e =int(np.random.random()*1000)
e

690

In [83]:
int(np.ceil(11.9))

12

In [84]:
#Splitting Arrays
a = np.floor(100*np.random.random((3,6)))
print(a)


[[81. 19. 52. 23. 25. 38.]
 [39. 35.  2. 49.  3.  8.]
 [ 0. 42. 35. 83. 71.  7.]]


In [85]:
f = np.hsplit(a,2)   # Split a into 2
print(f[0])
print("\n")
print(f[1])

[[81. 19. 52.]
 [39. 35.  2.]
 [ 0. 42. 35.]]


[[23. 25. 38.]
 [49.  3.  8.]
 [83. 71.  7.]]


In [102]:
#Copies and Views

# No Copy at All¶

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
b = a            # no new object is created
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [88]:
a[5] = 160
a

array([  0,   1,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

In [105]:
def rando(min,max):
    return(min+np.random.random()*max)
rando(20,22)

20.75012683974327

In [104]:
b

array([[  0,   1,   2,   3],
       [  4, 160,   6,   7],
       [  8,   9,  10,  11]])

In [106]:
b.shape = 3,4    # changes the shape of a.shape(3, 4)

In [107]:
a.shape

(12,)

In [108]:
c.base is a  
a.shape
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [112]:
c.shape =2,2              # a's shape doesn't change
print(a.shape)
c

ValueError: cannot reshape array of size 5 into shape (2,2)

In [ ]:
c[0,4] = 999                    # a's data changes
c

In [ ]:
a

In [ ]:
# Deep Copy

b = a.copy() 


In [ ]:
a[4] = 234
a

In [ ]:
b

In [ ]:
#floor - gives the bottom value 
#ceil - gives the upper number 
#rounds - gives the round value 
#random is a package as well as function 
#np.round(50+50+np.random.random())
np.round(np.random.random((2,2))*100)